version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  producer:
    build: ./producer
    container_name: producer-service
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  consumer-1:
    build: ./consumer-1
    container_name: consumer-1
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  consumer-2:
    build: ./consumer-2
    container_name: consumer-2
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  dlq-consumer:
    build: ./dlq-consumer
    container_name: dlq-consumer
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka
